language: julia
os:
  - linux
julia:
  - 1.3
codecov: true
coveralls: true

before_install:
  - julia --project -e 'import Pkg; Pkg.add(Pkg.PackageSpec(url="https://github.com/konkam/ExactWrightFisher.jl")); Pkg.add(Pkg.PackageSpec(url="https://github.com/konkam/FeynmanKacParticleFilters.jl"))'
