language: julia
os:
  - linux
julia:
  - 1.3
codecov: true
coveralls: true

before_install:
  using Pkg
  println("I am being built...")
  Pkg.add(PackageSpec(url="https://github.com/konkam/ExactWrightFisher.jl"))
  Pkg.add(PackageSpec(url="https://github.com/konkam/FeynmanKacParticleFilters.jl"))
